export default [
  { title: 'Daredevils only ... white water rafting!', href: '/activities', imgSrc: require('../../../public/images/rafting.jpg') },
  { title: 'Gorgeous Rooms :)', href: '/accommodation', imgSrc: require('../../../public/images/room_1.jpg') },
  { title: 'Gorgeous Rooms :)', href: '/accommodation', imgSrc: require('../../../public/images/bedroom.jpg') },
  { title: 'Gorgeous Rooms :)', href: '/accommodation', imgSrc: require('../../../public/images/double-bed.jpg') },
  { title: 'Plenty of bathroom next to each room', href: '/accommodation', imgSrc: require('../../../public/images/bp_bathroom.jpg') },
  { title: 'Plenty of bathroom next to each room', href: '/accommodation', imgSrc: require('../../../public/images/bp_bathroom_2.jpg') },
  { title: 'Plenty of bathroom next to each room', href: '/accommodation', imgSrc: require('../../../public/images/bp_red_bathroom.jpg') },
  { title: 'Campers welcome! Tent on you, facilities on us', href: '/accommodation', imgSrc: require('../../../public/images/campsite.jpg') },
  { title: 'Sundowners backpackers in all it\'s glory!', href: '/accommodation', imgSrc: require('../../../public/images/bp_front.jpg') },
  { title: 'Sundowners backpackers in all it\'s glory!', href: '/accommodation', imgSrc: require('../../../public/images/bp_panorama.jpg') },
  { title: 'The backpacker from the inside', href: '/accommodation', imgSrc: require('../../../public/images/bp_interior.jpg') },
  { title: 'Calling all master chefs', href: '/accommodation', imgSrc: require('../../../public/images/bp_kitchen.jpg') },
  { title: 'Comfy lounge for you to chill', href: '/accommodation', imgSrc: require('../../../public/images/bp_lounge.jpg') },
  { title: 'Pool is open 24/7, bring your own lifeguard', href: '/accommodation', imgSrc: require('../../../public/images/bp_pool_eve.jpg') },
  { title: 'Good times international style', imgSrc: require('../../../public/images/bp_fun.jpg') },
  { title: 'Stunning views', imgSrc: require('../../../public/images/distant_sunset.jpg') },
  { title: 'Stunning views', imgSrc: require('../../../public/images/mountain_sunset.jpg') },
  { title: 'Stunning views', imgSrc: require('../../../public/images/two_dudes_view.jpg') },
  { title: 'Funky hats welcomed', imgSrc: require('../../../public/images/freaky_hats_toast.jpg') },
  { title: 'Our funky chiefs, Paula and Sergio', imgSrc: require('../../../public/images/serg_paula_dressed.jpg') },
]
