import constants from '../../constants'
export default [
  { title: 'Daredevils only ... white water rafting!', href: '/activities', imgSrc: constants.BASE_IMAGE_PATH + '/bbq.jpg' },
  { title: 'Daredevils only ... white water rafting!', href: '/activities', imgSrc: constants.BASE_IMAGE_PATH + '/rafting.jpg' },
  { title: 'Gorgeous Rooms :)', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/room_1.jpg' },
  { title: 'Gorgeous Rooms :)', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bedroom.jpg' },
  { title: 'Gorgeous Rooms :)', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/double-bed.jpg' },
  { title: 'Plenty of bathroom next to each room', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bp_bathroom.jpg' },
  { title: 'Plenty of bathroom next to each room', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bp_bathroom_2.jpg' },
  { title: 'Plenty of bathroom next to each room', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bp_red_bathroom.jpg' },
  { title: 'Campers welcome! Tent on you, facilities on us', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/campsite.jpg' },
  { title: 'Sundowners backpackers in all it\'s glory!', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bp_front.jpg' },
  { title: 'Sundowners backpackers in all it\'s glory!', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bp_panorama.jpg' },
  { title: 'The backpacker from the inside', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bp_interior.jpg' },
  { title: 'Calling all master chefs', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bp_kitchen.jpg' },
  { title: 'Comfy lounge for you to chill', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bp_lounge.jpg' },
  { title: 'Pool is open 24/7, bring your own lifeguard', href: '/accommodation', imgSrc: constants.BASE_IMAGE_PATH + '/bp_pool_eve.jpg' },
  { title: 'Good times international style', imgSrc: constants.BASE_IMAGE_PATH + '/bp_fun.jpg' },
  { title: 'Stunning views', imgSrc: constants.BASE_IMAGE_PATH + '/distant_sunset.jpg' },
  { title: 'Stunning views', imgSrc: constants.BASE_IMAGE_PATH + '/mountain_sunset.jpg' },
  { title: 'Stunning views', imgSrc: constants.BASE_IMAGE_PATH + '/two_dudes_view.jpg' },
  { title: 'Funky hats welcomed', imgSrc: constants.BASE_IMAGE_PATH + '/freaky_hats_toast.jpg' },
  { title: 'Our funky chiefs, Paula and Sergio', imgSrc: constants.BASE_IMAGE_PATH + '/serg_paula_dressed.jpg' },
]
